name = "testflight-mail-to-telegram"
main = "src/index.js"
compatibility_date = "2023-02-02"

node_compat = true

[vars]
# - TG_SEND_IDS
TG_SEND_IDS = "123456789,-1001234567890"
# wrangler secret put TG_BOT_TOKEN
# - TG_BOT_TOKEN
# 1234567890:AAAAAAAAAA-AAAAAAAAAA-AAAAAAAAAA
# wrangler secret put FORWARD_TO_ADDRESS
# - FORWARD_TO_ADDRESS
# me@me.me